const PROFILE_AVATAR_PATH_PATTERN =
  // Only accept avatar paths generated by the profile uploader, not arbitrary
  // user-controlled objects that happen to live in the user's storage folder.
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/avatar-[a-z0-9]+-[a-z0-9]+\.(jpg|png|webp)$/i;

export const PROFILE_AVATAR_EXTENSIONS_BY_TYPE = new Map([
  ["image/jpeg", "jpg"],
  ["image/png", "png"],
  ["image/webp", "webp"],
]);

function isProfileAvatarStoragePathForUser(
  userId: string | null | undefined,
  storagePath: string | null | undefined
): boolean {
  if (!userId || !storagePath) {
    return false;
  }

  return (
    storagePath.startsWith(`${userId}/`) &&
    PROFILE_AVATAR_PATH_PATTERN.test(storagePath)
  );
}

export function normalizeProfileAvatarUrlForUser(
  userId: string | null | undefined,
  avatarUrl: string | null | undefined
): string | null {
  if (!userId || !avatarUrl) {
    return null;
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (!supabaseUrl) {
    return null;
  }

  try {
    const candidate = new URL(avatarUrl);
    const allowedOrigin = new URL(supabaseUrl).origin;
    const allowedPathPrefix = "/storage/v1/object/public/profile-avatars/";
    const storagePath = decodeURIComponent(candidate.pathname.slice(allowedPathPrefix.length));

    if (
      candidate.origin !== allowedOrigin ||
      !candidate.pathname.startsWith(allowedPathPrefix) ||
      !isProfileAvatarStoragePathForUser(userId, storagePath)
    ) {
      return null;
    }

    return `${candidate.origin}${allowedPathPrefix}${storagePath}`;
  } catch {
    return null;
  }
}

export function normalizeAnyProfileAvatarUrl(
  avatarUrl: string | null | undefined
): string | null {
  if (!avatarUrl) {
    return null;
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (!supabaseUrl) {
    return null;
  }

  try {
    const candidate = new URL(avatarUrl);
    const allowedOrigin = new URL(supabaseUrl).origin;
    const allowedPathPrefix = "/storage/v1/object/public/profile-avatars/";
    const storagePath = decodeURIComponent(candidate.pathname.slice(allowedPathPrefix.length));

    if (
      candidate.origin !== allowedOrigin ||
      !candidate.pathname.startsWith(allowedPathPrefix) ||
      !PROFILE_AVATAR_PATH_PATTERN.test(storagePath)
    ) {
      return null;
    }

    return `${candidate.origin}${allowedPathPrefix}${storagePath}`;
  } catch {
    return null;
  }
}

export function getProfileAvatarStoragePathForUser(
  userId: string | null | undefined,
  avatarUrl: string | null | undefined
): string | null {
  if (!userId || !avatarUrl) {
    return null;
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (!supabaseUrl) {
    return null;
  }

  try {
    const candidate = new URL(avatarUrl);
    const allowedOrigin = new URL(supabaseUrl).origin;
    const allowedPathPrefix = "/storage/v1/object/public/profile-avatars/";
    const storagePath = decodeURIComponent(candidate.pathname.slice(allowedPathPrefix.length));

    if (
      candidate.origin !== allowedOrigin ||
      !candidate.pathname.startsWith(allowedPathPrefix) ||
      !isProfileAvatarStoragePathForUser(userId, storagePath)
    ) {
      return null;
    }

    return storagePath;
  } catch {
    return null;
  }
}
